channels:
    - conda-forge
name:
    elf-dev
dependencies:
    - affogato >=0.3.2
    - h5py
    - imageio
    - intern
    - mrcfile
    - nifty >=1.1
    - numba
    - pandas
    - pip
    - python
    - scikit-image
    - skan
    - tqdm
    - vigra
    - zarr
    - z5py
