channels:
    - conda-forge
name:
    elf-dev
dependencies:
    - bioimage-cpp
    - h5py
    - imageio
    # Intern is an optional dependenciy that often crashes the CI.
    # We don't install it by default anymore.
    # - intern
    - mrcfile
    - numpy >=2
    - numba
    - pandas
    - pip
    - pooch
    - requests
    - scikit-image
    - scikit-learn
    - skan
    - tqdm
    - threadpoolctl
    - z5py
    - zarr >=2,<4
